# Eksploracja danych — Laboratorium 1
## Python do analizy danych: przypomnienie

**Cel zajęć:** odświeżyć Pythona i poznać podstawy narzędzi, których będziemy używać przez cały semestr: **NumPy**, **pandas** i **matplotlib**.

**Plan:**
1. Python w pigułce
2. NumPy
3. pandas — pierwsze kroki
4. Wykresy w matplotlib

**Zadania** mają dwa poziomy:
- 🟢 **podstawowe** — obowiązkowe,
- 🔵 **dla ambitnych** — dodatkowe.

**Jak pracować:** w Colabie wybierz *Plik → Zapisz kopię na Dysku*, rozwiąż zadania w miejscach oznaczonych `# TODO`, a gotowy notatnik umieść w swoim repozytorium na GitHubie.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

plt.rcParams.update({"figure.figsize": (7, 4), "font.size": 12})

---
# 1. Python w pigułce

In [1]:
# Listy, indeksowanie i wycinanie (slicing)
temperatury = [12.5, 14.0, 9.8, 17.3, 15.1]

print(temperatury[0])     # pierwszy element
print(temperatury[-1])    # ostatni element
print(temperatury[1:3])   # elementy o indeksach 1 i 2
print(len(temperatury))

12.5
15.1
[14.0, 9.8]
5

In [2]:
# Pętla for, enumerate i zip
dni = ["pon", "wt", "śr", "czw", "pt"]

for i, t in enumerate(temperatury):
    print(f"[{i}] -> {t}")

for dzien, t in zip(dni, temperatury):
    print(f"{dzien}: {t:.1f} °C")   # :.1f — jedna cyfra po przecinku

[0] -> 12.5
[1] -> 14.0
[2] -> 9.8
[3] -> 17.3
[4] -> 15.1
pon: 12.5 °C
wt: 14.0 °C
śr: 9.8 °C
czw: 17.3 °C
pt: 15.1 °C

In [3]:
# Słownik: klucz -> wartość
miasto = {"nazwa": "Łódź", "wojewodztwo": "łódzkie", "ludnosc_2021": 670_642}

print(miasto["nazwa"])
for klucz, wartosc in miasto.items():
    print(klucz, "=", wartosc)

Łódź
nazwa = Łódź
wojewodztwo = łódzkie
ludnosc_2021 = 670642

In [4]:
# Funkcja z docstringiem
def potega(lista, p):
    """
    Podnosi każdy element listy do potęgi p.

    Parametry:
    - lista (list): lista liczb,
    - p (int | float): wykładnik.

    Zwraca:
    - list: nowa lista z elementami podniesionymi do potęgi p.
    """
    wynik = []
    for x in lista:
        wynik.append(x ** p)
    return wynik


print(potega([1, 2, 3, 4], 3))
help(potega)   # w Jupyterze/Colabie także: potega?

[1, 8, 27, 64]
Help on function potega in module __main__:

potega(lista, p)
    Podnosi każdy element listy do potęgi p.

    Parametry:
    - lista (list): lista liczb,
    - p (int | float): wykładnik.

    Zwraca:
    - list: nowa lista z elementami podniesionymi do potęgi p.

### List comprehension

Zwięzły sposób tworzenia list:
```python
[wyrażenie for element in kolekcja if warunek]
```

In [5]:
print([x ** 2 for x in range(6)])
print([x ** 2 for x in range(6) if x % 2 == 0])

[0, 1, 4, 9, 16, 25]
[0, 4, 16]

### 🟢 Zadanie 1: średnia i mediana

Lista `dlugosc_zycia` zawiera oczekiwaną długość życia (w latach) w 14 krajach.

1. Napisz funkcję `srednia(liczby)`, która zwraca średnią arytmetyczną — **bez** używania `sum()` i NumPy (użyj pętli).
2. Napisz funkcję `mediana(liczby)`, która zwraca medianę. Pamiętaj o przypadku parzystej i nieparzystej liczby elementów. Wskazówka: `sorted()`.
3. Porównaj wyniki z `np.mean()` i `np.median()`.

🔵 **Dla ambitnych:** niech obie funkcje zgłaszają czytelny błąd (`raise ValueError(...)`), gdy lista jest pusta.

In [7]:
dlugosc_zycia = [81.8, 81.0, 82.6, 83.0, 81.8, 84.3, 82.8, 81.9, 82.2, 82.0, 82.7, 79.8, 83.3, 82.0]

In [9]:
import numpy as np

def srednia(liczby):
  sum = 0;
  for l in liczby:
    sum += l
  return sum / len(liczby)

def mediana(liczby):
  if len(liczby) % 2 == 1:
    return sorted(liczby)[len(liczby) // 2]
  else:
    return (sorted(liczby)[len(liczby) // 2 - 1] + sorted(liczby)[len(liczby) // 2]) / 2


print("moja średnia:", srednia(dlugosc_zycia), " NumPy:", np.mean(dlugosc_zycia))
print("moja mediana:", mediana(dlugosc_zycia), " NumPy:", np.median(dlugosc_zycia))

moja średnia: 82.22857142857143  NumPy: 82.22857142857143
moja mediana: 82.1  NumPy: 82.1

### 🟢 Zadanie 2: zliczanie

Napisz funkcję `zlicz(lista)`, która zwraca słownik: element → liczba jego wystąpień.

Przykład: `zlicz(["a", "b", "a", "c", "a"])` → `{"a": 3, "b": 1, "c": 1}`

Sprawdź ją na liście `oceny`. Która ocena występuje najczęściej?

In [11]:
oceny = [4, 3, 5, 4, 4, 2, 3, 5, 4, 3, 4, 5, 3, 4]

def zlicz(lista):
    dict = {}
    for el in lista:
        if el in dict:
            dict[el] += 1
        else:
            dict[el] = 1
    return dict

zlicz(oceny)

{4: 6, 3: 4, 5: 3, 2: 1}

### 🟢 Zadanie 3: list comprehension

Dla listy `temperatury` (w °C) z początku notatnika:

1. Utwórz listę temperatur w stopniach Fahrenheita: $F = \frac{9}{5}C + 32$.
2. Utwórz listę tylko tych temperatur (w °C), które są wyższe niż 13 °C.
3. Utwórz listę napisów w postaci `"pon: 12.5 °C"` (wskazówka: `zip`).

Każdy punkt rozwiąż **jedną** linią.

In [13]:
print([t * 9 / 5 + 32 for t in temperatury])
print([t for t in temperatury if t > 13])
print([f"{dzien}: {t:.1f} °C" for dzien, t in zip(dni, temperatury)])

[54.5, 57.2, 49.64, 63.14, 59.18]
[14.0, 17.3, 15.1]
['pon: 12.5 °C', 'wt: 14.0 °C', 'śr: 9.8 °C', 'czw: 17.3 °C', 'pt: 15.1 °C']

---
# 2. NumPy

**NumPy** to podstawa obliczeń numerycznych w Pythonie — na nim zbudowane są pandas, scikit-learn i wiele innych bibliotek. Kluczowa idea: **wektoryzacja**, czyli operacje na całych tablicach naraz, bez pisania pętli.

In [14]:
a = np.array([1, 2, 3, 4, 5])
print(a, a.dtype, a.shape)

print(np.arange(0, 10, 2))       # od 0 do 10 (bez 10) co 2
print(np.linspace(0, 1, 5))      # 5 równo rozłożonych punktów od 0 do 1 (z 1)
print(np.zeros(3), np.ones(3))

[1 2 3 4 5] int64 (5,)
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[0. 0. 0.] [1. 1. 1.]

### Lista ≠ tablica

Te same operatory działają inaczej na listach i na tablicach NumPy:

In [15]:
lista = [1, 2, 3]
tablica = np.array([1, 2, 3])

print("lista * 2   =", lista * 2)      # powtórzenie listy!
print("tablica * 2 =", tablica * 2)    # mnożenie każdego elementu
print("lista + lista     =", lista + lista)        # sklejenie list
print("tablica + tablica =", tablica + tablica)    # dodawanie element po elemencie

lista * 2   = [1, 2, 3, 1, 2, 3]
tablica * 2 = [2 4 6]
lista + lista     = [1, 2, 3, 1, 2, 3]
tablica + tablica = [2 4 6]

In [16]:
# Maski logiczne i agregacje
pomiary = np.array([7, 5, 4, 8, 4, 2, 9, 4, 100])

print("maska > 5:", pomiary > 5)
print("wartości > 5:", pomiary[pomiary > 5])
print("ile > 5:", (pomiary > 5).sum())

print("min, max:", pomiary.min(), pomiary.max())
print("średnia:", pomiary.mean())
print("mediana:", np.median(pomiary))
print("odchylenie standardowe:", pomiary.std())

maska > 5: [ True False False  True False False  True False  True]
wartości > 5: [  7   8   9 100]
ile > 5: 4
min, max: 2 100
średnia: 15.88888888888889
mediana: 5.0
odchylenie standardowe: 29.812169194789657

### Liczby losowe

Używamy **generatora** `np.random.default_rng()`. Ustalone ziarno (`seed`) daje powtarzalne wyniki.

In [17]:
rng = np.random.default_rng(seed=42)

print(rng.integers(1, 7, size=10))        # 10 rzutów kostką: liczby całkowite z [1, 7)
print(rng.uniform(0, 1, size=3))          # 3 liczby z rozkładu jednostajnego na [0, 1)
print(rng.normal(loc=0, scale=1, size=3)) # 3 liczby z rozkładu normalnego N(0, 1)

[1 5 4 3 3 6 1 5 2 1]
[0.97562235 0.7611397  0.78606431]
[-0.01680116 -0.85304393  0.87939797]

### 🟢 Zadanie 4: dlaczego NumPy?

Zsumuj liczby od 1 do 1 000 000 na **cztery sposoby** i zmierz czas każdego z nich magiczną komendą `%timeit`:

1. pętla `for`,
2. `sum()` na liście zbudowanej przez list comprehension,
3. `sum(range(...))`,
4. NumPy: `np.arange(...).sum()`.

Sprawdź, czy wszystkie dają ten sam wynik. Który sposób jest najszybszy i **dlaczego**? Odpowiedz w komórce tekstowej.

In [25]:
N = 1_000_000

def suma_petla(n):
    sum = 0
    for i in range(n+1):
        sum += i
    return sum

def suma_comprehension(n):
    return sum([i for i in range(n+1)])

def suma_range(n):
    return sum(range(n+1))

def suma_numpy(n):
    return np.arange(n+1).sum()

print(suma_numpy(N))
print(suma_petla(N) == suma_comprehension(N) == suma_range(N) == suma_numpy(N))

%timeit suma_petla(N)
%timeit suma_comprehension(N)
%timeit suma_range(N)
%timeit suma_numpy(N)

500000500000
True
74.2 ms ± 20.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
63.6 ms ± 1.63 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
24.7 ms ± 5.45 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
1.35 ms ± 297 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

### Odpowiedź do Zadania 4:

**Najszybszym sposobem** jest użycie biblioteki NumPy: `np.arange(n+1).sum()`.

**Dlaczego?**
1. **Wektoryzacja i implementacja w C:** NumPy wykonuje operacje bezpośrednio w skompilowanym kodzie C. Pętla sumująca wykonywana jest na poziomie niskopoziomowym, co eliminuje narzut związany z interpretowaniem kodu Pythona przy każdej iteracji.
2. **Ciągłość pamięci:** Tablice NumPy przechowują dane w ciągłym bloku pamięci, co pozwala procesorowi na efektywne wykorzystanie pamięci podręcznej (cache) i wektoryzację instrukcji (SIMD).
3. **Brak obiektów Pythona:** W standardowych listach Pythona i pętlach każda liczba jest osobnym obiektem Pythona, co wiąże się z ciągłym tworzeniem i niszczeniem obiektów oraz sprawdzaniem ich typów (dynamic typing). NumPy operuje bezpośrednio na prymitywnych typach danych (np. 64-bitowych liczbach całkowitych).

### 🟢 Zadanie 5: operacje na tablicach

Dana jest tablica `x` z pomiarami temperatury (°C).

1. Policz średnią, odchylenie standardowe, minimum i maksimum.
2. Wybierz pomiary wyższe od średniej. Ile ich jest?
3. **Normalizacja min–max:** przeskaluj `x` do przedziału $[0, 1]$: $\;x' = \dfrac{x - x_{\min}}{x_{\max} - x_{\min}}$
4. **Standaryzacja:** $\;z = \dfrac{x - \bar{x}}{s}$. Sprawdź, że wynik ma średnią ≈ 0 i odchylenie standardowe ≈ 1.

Wszystko bez pętli!

In [31]:
x = np.array([12.5, 14.0, 9.8, 17.3, 15.1, 11.2, 18.6, 16.0, 13.4, 10.9])

# 1. Statystyki
srednia_x = x.mean()
odch_std_x = x.std()
min_x = x.min()
max_x = x.max()

print("1. Statystyki:")
print(f"   Średnia: {srednia_x:.2f}")
print(f"   Odchylenie standardowe: {odch_std_x:.2f}")
print(f"   Minimum: {min_x:.2f}")
print(f"   Maksimum: {max_x:.2f}\n")

# 2. Pomiary wyższe od średniej
wyzsze_od_sredniej = x[x > srednia_x]
print("2. Pomiary wyższe od średniej:")
print(f"   Wartości: {wyzsze_od_sredniej}")
print(f"   Liczba pomiarów: {len(wyzsze_od_sredniej)}\n")

# 3. Normalizacja min-max
x_normalizowane = (x - min_x) / (max_x - min_x)
print("3. Normalizacja min-max (przedział [0, 1]):")
print(f"   x' = {x_normalizowane}\n")

# 4. Standaryzacja
z = (x - srednia_x) / odch_std_x
print("4. Standaryzacja:")
print(f"   z = {z}")
print(f"   Średnia wyniku: {z.mean():.2f} (oczekiwano 0)")
print(f"   Odchylenie standardowe wyniku: {z.std():.2f} (oczekiwano 1)")

1. Statystyki:
   Średnia: 13.88
   Odchylenie standardowe: 2.74
   Minimum: 9.80
   Maksimum: 18.60

2. Pomiary wyższe od średniej:
   Wartości: [14.  17.3 15.1 18.6 16. ]
   Liczba pomiarów: 5

3. Normalizacja min-max (przedział [0, 1]):
   x' = [0.30681818 0.47727273 0.         0.85227273 0.60227273 0.15909091
 1.         0.70454545 0.40909091 0.125     ]

4. Standaryzacja:
   z = [-0.50452402  0.04387165 -1.49163622  1.25034213  0.44602848 -0.97980026
  1.72561837  0.77506588 -0.17548661 -1.0894794 ]
   Średnia wyniku: -0.00 (oczekiwano 0)
   Odchylenie standardowe wyniku: 1.00 (oczekiwano 1)

### 🟢 Zadanie 6: rzuty kostką

1. Zasymuluj 10 000 rzutów kostką do gry (`rng.integers`).
2. Policz, ile razy wypadła każda liczba oczek (wskazówka: `np.unique(..., return_counts=True)`) i jaki to odsetek wszystkich rzutów.
3. Policz średnią liczbę oczek. Jakiej wartości się spodziewasz?

🔵 **Dla ambitnych:** zasymuluj 10 000 rzutów **dwiema** kostkami i policz rozkład sumy oczek. Która suma wypada najczęściej i dlaczego?

In [32]:
rng = np.random.default_rng(seed=1)

# 1. Symulacja 10 000 rzutów kostką
rzuty = rng.integers(1, 7, size=10000)

# 2. Zliczanie wyników
oczka, liczba_wystapien = np.unique(rzuty, return_counts=True)
odsetki = (liczba_wystapien / 10000) * 100

print("--- Część podstawowa: Rzuty jedną kostką ---")
for o, l, ods in zip(oczka, liczba_wystapien, odsetki):
    print(f"Oczka: {o} | Liczba rzutów: {l:4d} | Odsetek: {ods:5.2f}%")

# 3. Średnia liczba oczek
srednia_oczek = rzuty.mean()
print(f"\nŚrednia liczba oczek: {srednia_oczek:.4f} (oczekiwana wartość teoretyczna to 3.5)\n")

--- Część podstawowa: Rzuty jedną kostką ---
Oczka: 1 | Liczba rzutów: 1695 | Odsetek: 16.95%
Oczka: 2 | Liczba rzutów: 1634 | Odsetek: 16.34%
Oczka: 3 | Liczba rzutów: 1668 | Odsetek: 16.68%
Oczka: 4 | Liczba rzutów: 1628 | Odsetek: 16.28%
Oczka: 5 | Liczba rzutów: 1717 | Odsetek: 17.17%
Oczka: 6 | Liczba rzutów: 1658 | Odsetek: 16.58%

Średnia liczba oczek: 3.5012 (oczekiwana wartość teoretyczna to 3.5)

---
# 3. pandas — pierwsze kroki

**pandas** służy do pracy z danymi tabelarycznymi. Podstawowe struktury:
- `Series` — jedna kolumna (wektor z etykietami),
- `DataFrame` — tabela, czyli zbiór kolumn o wspólnym indeksie.

### DataFrame ze słownika

In [35]:
import pandas as pd
dane = {
    "miasto": ["Warszawa", "Kraków", "Łódź", "Wrocław", "Poznań"],
    "ludnosc_2021": [1_860_281, 800_653, 670_642, 674_079, 546_859],
    "powierzchnia_km2": [517, 327, 293, 293, 262],
}
miasta = pd.DataFrame(dane)
miasta

     miasto  ludnosc_2021  powierzchnia_km2
0  Warszawa       1860281               517
1    Kraków        800653               327
2      Łódź        670642               293
3   Wrocław        674079               293
4    Poznań        546859               262

In [36]:
# Nowa kolumna obliczona z innych kolumn
miasta["gestosc"] = miasta["ludnosc_2021"] / miasta["powierzchnia_km2"]
miasta.sort_values("gestosc", ascending=False)

     miasto  ludnosc_2021  powierzchnia_km2      gestosc
0  Warszawa       1860281               517  3598.222437
1    Kraków        800653               327  2448.480122
3   Wrocław        674079               293  2300.610922
2      Łódź        670642               293  2288.880546
4    Poznań        546859               262  2087.248092

In [37]:
# Zapis do pliku CSV i ponowne wczytanie
miasta.to_csv("miasta.csv", index=False)
pd.read_csv("miasta.csv")

     miasto  ludnosc_2021  powierzchnia_km2      gestosc
0  Warszawa       1860281               517  3598.222437
1    Kraków        800653               327  2448.480122
2      Łódź        670642               293  2288.880546
3   Wrocław        674079               293  2300.610922
4    Poznań        546859               262  2087.248092

### Prawdziwy zbiór danych: `tips`

Zbiór `tips` zawiera 244 rachunki z restauracji, zapisane przez kelnera w ciągu kilku tygodni.

| kolumna | znaczenie |
|---|---|
| `total_bill` | kwota rachunku (USD) |
| `tip` | napiwek (USD) |
| `sex` | płeć płacącego |
| `smoker` | czy przy stoliku palono |
| `day` | dzień tygodnia |
| `time` | pora: lunch / obiad |
| `size` | liczba osób przy stoliku |

In [38]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### Pierwszy rzut oka na dane

In [39]:
print(df.shape)     # (liczba wierszy, liczba kolumn)
df.info()           # typy kolumn i liczba niepustych wartości

(244, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [40]:
df.describe()       # statystyki opisowe kolumn liczbowych

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

### Wybieranie kolumn i wierszy

In [41]:
df["tip"].head()                    # jedna kolumna -> Series

0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
Name: tip, dtype: float64

In [42]:
df[["total_bill", "tip"]].head()    # kilka kolumn -> DataFrame (podwójne nawiasy!)

   total_bill   tip
0       16.99  1.01
1       10.34  1.66
2       21.01  3.50
3       23.68  3.31
4       24.59  3.61

In [43]:
print(df["tip"].mean(), df["tip"].max())   # metody kolumny

2.99827868852459 10.0

### `loc` czy `iloc`?

- `iloc` — wybiera po **pozycji** (0, 1, 2, …),
- `loc` — wybiera po **etykiecie indeksu**.

Póki indeks to 0, 1, 2, …, oba dają to samo. Różnica wychodzi na jaw po posortowaniu:

In [44]:
posortowane = df.sort_values("tip", ascending=False)
posortowane.head(3)

     total_bill    tip   sex smoker  day    time  size
170       50.81  10.00  Male    Yes  Sat  Dinner     3
212       48.33   9.00  Male     No  Sat  Dinner     4
23        39.42   7.58  Male     No  Sat  Dinner     4

In [45]:
print("iloc[0] — pierwszy wiersz po posortowaniu (najwyższy napiwek):")
print(posortowane.iloc[0], "\n")

print("loc[0] — wiersz o etykiecie 0 (pierwszy rachunek w danych):")
print(posortowane.loc[0])

iloc[0] — pierwszy wiersz po posortowaniu (najwyższy napiwek):
total_bill     50.81
tip             10.0
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               3
Name: 170, dtype: object

loc[0] — wiersz o etykiecie 0 (pierwszy rachunek w danych):
total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

### Filtrowanie

Warunki łączymy operatorami `&` (i), `|` (lub), `~` (nie) — każdy warunek **w nawiasach**.

In [46]:
duze_rachunki = df[df["total_bill"] > 40]
duze_rachunki

     total_bill    tip     sex smoker   day    time  size
59        48.27   6.73    Male     No   Sat  Dinner     4
95        40.17   4.73    Male    Yes   Fri  Dinner     4
102       44.30   2.50  Female    Yes   Sat  Dinner     3
142       41.19   5.00    Male     No  Thur   Lunch     5
156       48.17   5.00    Male     No   Sun  Dinner     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
182       45.35   3.50    Male    Yes   Sun  Dinner     3
184       40.55   3.00    Male    Yes   Sun  Dinner     2
197       43.11   5.00  Female    Yes  Thur   Lunch     4
212       48.33   9.00    Male     No   Sat  Dinner     4

In [47]:
sobota_obiad = df[(df["day"] == "Sat") & (df["time"] == "Dinner")]
print(len(sobota_obiad), "rachunków w sobotę na obiedzie")

87 rachunków w sobotę na obiedzie

In [48]:
# Z .loc: wiersze spełniające warunek i wybrane kolumny
df.loc[df["size"] >= 5, ["total_bill", "tip", "size"]]

     total_bill   tip  size
125       29.80  4.20     6
141       34.30  6.70     6
142       41.19  5.00     5
143       27.05  5.00     6
155       29.85  5.14     5
156       48.17  5.00     6
185       20.69  5.00     5
187       30.46  2.00     5
216       28.15  3.00     5

In [49]:
df["day"].value_counts()    # ile razy występuje każda wartość

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

### 🟢 Zadanie 7: pytania do zbioru `tips`

Odpowiedz kodem:

1. Ile wierszy i kolumn ma zbiór? Jakie są nazwy kolumn?
2. Jaki jest średni, najmniejszy i największy rachunek?
3. Ile rachunków pochodzi z niedzieli (`"Sun"`)?
4. Pokaż 5 najwyższych rachunków.
5. Dodaj kolumnę `tip_pct` — napiwek jako procent rachunku. Jaki jest średni `tip_pct`?
6. Ile rachunków ma napiwek wyższy niż 20% rachunku?

🔵 **Dla ambitnych:**

7. Jaki jest średni `tip_pct` dla lunchu, a jaki dla obiadu? (Użyj filtrowania.)
8. Dodaj kolumnę `rachunek_na_osobe`. Przy którym stoliku rachunek na osobę był najwyższy?

In [51]:
# 1. Wymiary zbioru i nazwy kolumn
wiersze, kolumny = df.shape
nazwy_kolumn = list(df.columns)
print("1. Informacje o zbiorze:")
print(f"   Liczba wierszy: {wiersze}, Liczba kolumn: {kolumny}")
print(f"   Nazwy kolumn: {nazwy_kolumn}\n")

# 2. Statystyki rachunku (total_bill)
srednia_bill = df["total_bill"].mean()
min_bill = df["total_bill"].min()
max_bill = df["total_bill"].max()
print("2. Statystyki rachunku (total_bill):")
print(f"   Średni: {srednia_bill:.2f} USD")
print(f"   Najmniejszy: {min_bill:.2f} USD")
print(f"   Największy: {max_bill:.2f} USD\n")

# 3. Rachunki z niedzieli
niedziela_count = (df["day"] == "Sun").sum()
print(f"3. Liczba rachunków w niedzielę: {niedziela_count}\n")

# 4. 5 najwyższych rachunków
print("4. Pięć najwyższych rachunków:")
print(df.sort_values("total_bill", ascending=False).head(5)[["total_bill", "tip", "sex", "day"]].to_string(index=False))
print()

# 5. Nowa kolumna tip_pct i jej średnia
df["tip_pct"] = (df["tip"] / df["total_bill"]) * 100
srednia_tip_pct = df["tip_pct"].mean()
print(f"5. Średni procent napiwku (tip_pct): {srednia_tip_pct:.2f}%\n")

# 6. Rachunki z napiwkiem wyższym niż 20% rachunku
napiwek_ponad_20_proc = (df["tip_pct"] > 20).sum()
print(f"6. Liczba rachunków z napiwkiem > 20%: {napiwek_ponad_20_proc}\n")

1. Informacje o zbiorze:
   Liczba wierszy: 244, Liczba kolumn: 9
   Nazwy kolumn: ['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size', 'tip_pct', 'rachunek_na_osobe']

2. Statystyki rachunku (total_bill):
   Średni: 19.79 USD
   Najmniejszy: 3.07 USD
   Największy: 50.81 USD

3. Liczba rachunków w niedzielę: 76

4. Pięć najwyższych rachunków:
 total_bill   tip  sex day
      50.81 10.00 Male Sat
      48.33  9.00 Male Sat
      48.27  6.73 Male Sat
      48.17  5.00 Male Sun
      45.35  3.50 Male Sun

5. Średni procent napiwku (tip_pct): 16.08%

6. Liczba rachunków z napiwkiem > 20%: 39